apiVersion: v1
kind: Service
metadata:
  name: cnn-class-service
  namespace: demo
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 31334
  selector:
    app: cnn-class
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnn-classification-u280-thr
  namespace: demo
spec:
  selector:
    matchLabels:
      app: cnn-class
  replicas: 1
  template:
    metadata:
      labels:
        app: cnn-class
    spec:
      hostNetwork: true
      containers:
      - name: cnn-classification-u280-thr
        image: iwita/cnn-classification:alveo-u280-thr
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /opt/xilinx/overlaybins
          name: overlaybins
        - mountPath: /dev/shm
          name: shm
        - mountPath: /opt/xilinx/dsa
          name: dsa
        - mountPath: /etc/xbutler
          name: xbutler
        resources:
          limits:
            xilinx.com/fpga-xilinx_u280_xdma_201920_3-1579649056: 1
        # command: ["/bin/bash", "-c", "--"]
        # args: ["while true; do sleep 1000s; done;"]
        ports:
        - containerPort: 3000
      volumes:
      - name: overlaybins
        hostPath:
          path: /opt/xilinx/overlaybins
      - name: shm
        hostPath:
          path: /dev/shm
      - name: dsa
        hostPath:
          path: /opt/xilinx/dsa
      - name: xbutler
        hostPath:
          path: /etc/xbutler
