FROM python:3.6.9

RUN pip install opencv-python requests flask matplotlib
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

RUN mkdir -p /home/Documents
# That is for some kind of bug found on cv2

COPY testing_0.png /home/Documents
COPY client.py /home/Documents
WORKDIR /home/Documents

ENV FLASK_APP=rest-cnn.py
EXPOSE 3001

# CMD source /workspace/setup.sh $DEVICE && /usr/bin/python3 rest-cnn.py
# CMD /usr/bin/python3 rest-cnn.py
CMD sleep infinity
