apiVersion: v1
kind: Service
metadata:
  name: lstm-service
  labels:
    app: netw-intr-u280
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 31333
  selector:
    app: netw-intr-u280