apiVersion: v1
kind: Service
metadata:
  name: lstm-service
  namespace: demo
  labels:
    app: netw-intr
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 31333
  selector:
    app: netw-intr